# Generated by Django 3.2.4 on 2021-06-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=32)),
                ('level', models.CharField(choices=[('easy', '初級'), ('normal', '中級'), ('hard', '上級')], default='easy', max_length=8)),
                ('score', models.IntegerField()),
                ('is_checked', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
